# name of the action
name: bash

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@20190331160914
      with:
        name: target/vela-sample:bash
        workdir: plugins/bash
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
