# name of the action
name: bash

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - master

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: bash:latest
    steps:
    - name: clone
      uses: actions/checkout@v2

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-sample:bash
        workdir: plugins/bash
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
