# name of the action
name: go

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: install go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: '>=1.19.0'

    - name: build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: '0'
      run: |
        go build \
          -ldflags '-extldflags "-static"' \
          -o plugins/go/vela-sample \
          plugins/go/main.go

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
      with:
        name: target/vela-sample:go
        workdir: plugins/go
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
