# name of the action
name: go

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'

    - name: build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: '0'
      run: |
        go build \
          -ldflags '-extldflags "-static"' \
          -o plugins/go/vela-sample \
          plugins/go/main.go

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: target/vela-sample:go
        workdir: plugins/go
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
