# name of the action
name: python

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: setup python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: '3.13'

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@742a180fa47f3adfb5115902ae4955acc6ad769b # v4
      with:
        name: target/vela-sample:python
        workdir: plugins/python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
