# name of the action
name: python

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@20190331160914
      with:
        name: target/vela-sample:python
        workdir: plugins/python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
