# name of the action
name: ruby

# trigger on pull_request or push events
on:
  pull_request:
  push:
    branches-ignore:
     - main

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: docker
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: target/vela-sample:ruby
        workdir: plugins/ruby
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
